// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// RunSharedFunction
double RunSharedFunction(double x);
RcppExport SEXP SharedLibrariesExample_RunSharedFunction(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    __result = Rcpp::wrap(RunSharedFunction(x));
    return __result;
END_RCPP
}
// RunSharedTemplateFunction
double RunSharedTemplateFunction(double x);
RcppExport SEXP SharedLibrariesExample_RunSharedTemplateFunction(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    __result = Rcpp::wrap(RunSharedTemplateFunction(x));
    return __result;
END_RCPP
}
// RunSharedIntTemplateFunction
double RunSharedIntTemplateFunction(int x);
RcppExport SEXP SharedLibrariesExample_RunSharedIntTemplateFunction(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    __result = Rcpp::wrap(RunSharedIntTemplateFunction(x));
    return __result;
END_RCPP
}
// RunSharedDoubleTemplateFunction
double RunSharedDoubleTemplateFunction(double x);
RcppExport SEXP SharedLibrariesExample_RunSharedDoubleTemplateFunction(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    __result = Rcpp::wrap(RunSharedDoubleTemplateFunction(x));
    return __result;
END_RCPP
}
// RunSharedFunctor
double RunSharedFunctor(double x);
RcppExport SEXP SharedLibrariesExample_RunSharedFunctor(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    __result = Rcpp::wrap(RunSharedFunctor(x));
    return __result;
END_RCPP
}
// RunSharedTemplateClass
double RunSharedTemplateClass(double x);
RcppExport SEXP SharedLibrariesExample_RunSharedTemplateClass(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    __result = Rcpp::wrap(RunSharedTemplateClass(x));
    return __result;
END_RCPP
}
