// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// RunSharedFunction
double RunSharedFunction(double x);
RcppExport SEXP SharedLibrariesExample_RunSharedFunction(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    __result = Rcpp::wrap(RunSharedFunction(x));
    return __result;
END_RCPP
}
// RunSharedTemplateFunction
double RunSharedTemplateFunction(double x);
RcppExport SEXP SharedLibrariesExample_RunSharedTemplateFunction(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    __result = Rcpp::wrap(RunSharedTemplateFunction(x));
    return __result;
END_RCPP
}
// RunSharedTemplateFunctionInt
double RunSharedTemplateFunctionInt(int x);
RcppExport SEXP SharedLibrariesExample_RunSharedTemplateFunctionInt(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    __result = Rcpp::wrap(RunSharedTemplateFunctionInt(x));
    return __result;
END_RCPP
}
