# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RunSharedFunction <- function(x) {
    .Call('SharedLibrariesExample_RunSharedFunction', PACKAGE = 'SharedLibrariesExample', x)
}

RunSharedTemplateFunction <- function(x) {
    .Call('SharedLibrariesExample_RunSharedTemplateFunction', PACKAGE = 'SharedLibrariesExample', x)
}

RunSharedIntTemplateFunction <- function(x) {
    .Call('SharedLibrariesExample_RunSharedIntTemplateFunction', PACKAGE = 'SharedLibrariesExample', x)
}

RunSharedDoubleTemplateFunction <- function(x) {
    .Call('SharedLibrariesExample_RunSharedDoubleTemplateFunction', PACKAGE = 'SharedLibrariesExample', x)
}

